"""Create evidence HTML and plots from verified native records; use a plotting Python runtime."""
import argparse,hashlib,html,json,shutil,struct,zlib
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
p=argparse.ArgumentParser();p.add_argument('--session',required=True);p.add_argument('--repo',required=True);a=p.parse_args()
root=Path(a.session).resolve();repo=Path(a.repo).resolve();report=root/'report';media=report/'media/slice-05';media.mkdir(parents=True,exist_ok=True)
load=lambda f:json.loads(f.read_text(encoding='utf-8-sig'))
verified=load(sorted(report.glob('verification-05-*/checks.json'))[-1]);ui=load(sorted(report.glob('ui-05-*/checks.json'))[-1]);ui_dir=sorted(report.glob('ui-05-*'))[-1]
assert verified['checks']['allCompleteScopedPassed'] and all(v is True or isinstance(v,dict) for v in ui['checks'].values()) and not ui['errors']
build=load(sorted(report.glob('build-*.json'))[-1]);source=load(report/build['sourceRecord'])
assert build['sha256']==hashlib.sha256((root/'build/bin/RoR.exe').read_bytes()).hexdigest().upper()
for name,digest in source['nativeSourceHashes'].items():assert hashlib.sha256((repo/name).read_bytes()).hexdigest().upper()==digest,name
def records(path):
 data=path.read_bytes();assert data[:8]==b'RORTRIAL' and struct.unpack_from('<II',data,8)==(2,2080);at=16;values=[]
 while data[at:at+4]==b'DATA':
  n,size,crc=struct.unpack_from('<III',data,at+4);block=data[at+16:at+16+size]
  assert size==n*2080 and zlib.crc32(block)==crc and data[at+16+size:at+20+size]==b'DONE'
  for i in range(n):
   r=block[i*2080:(i+1)*2080];d=lambda n:struct.unpack_from('<d',r,n)[0]
   values.append(dict(tick=struct.unpack_from('<Q',r)[0],time=d(24)*struct.unpack_from('<Q',r)[0],x=d(40)-501,
    velocity=d(64)/d(32),force=d(88),elasticForce=d(408),correction=d(520),kinetic=d(144),storage=d(1160),restPort=d(1232),removalPort=d(1240),closure=d(1168)))
  at+=20+size
 assert data[at:at+4]==b'END!' and struct.unpack_from('<QQI',data,at+4)==(len(values),0,0) and len(data)==at+24
 return values
scenarios=['yield-tension-v1','yield-compression-v1','fracture-v1','protected-beam-v1'];selected={};summaries=[]
for scenario in scenarios:
 v=next(v for v in verified['runs'] if v['definition']['scenario']==scenario and v['definition']['durationSeconds']==1)
 selected[scenario]=v;event=v['metrics']['beamTransitions']['events'][0]
 summaries.append(dict(scenario=scenario,id=v['id'],event=event,qualification=v['metrics']['qualification'],records=v['metrics']['records'],executableSha256=v['executableSha256']))
 for suffix in ['ledger.png']:shutil.copy2(ui_dir/(scenario+'-'+suffix),media/(scenario+'-'+suffix))
for name in ['qualification.png','dashboard-desktop.png','dashboard-mobile.png']:shutil.copy2(ui_dir/name,media/name)
plt.rcParams.update({'font.size':10,'axes.spines.top':False,'axes.spines.right':False,'figure.facecolor':'#ffffff'})
for mode in ['energy','forces','motion']:
 fig,axes=plt.subplots(2,2,figsize=(12,7),layout='constrained')
 for ax,(scenario,v) in zip(axes.flat,selected.items()):
  data=records(Path(v['archivePath'])/'steps.rort');t=[x['time'] for x in data]
  if mode=='energy':
   ax.plot(t,[x['kinetic'] for x in data],label='Node kinetic',color='#1e6baa');ax.plot(t,[x['storage'] for x in data],label='Active linear storage',color='#159887');ax.set_ylabel('J')
  elif mode=='forces':
   part=data[:20];t=[x['time']*1000 for x in part]
   for key,label,color in [('force','Applied X','#159887'),('elasticForce','Elastic channel X','#1e6baa'),('correction','Correction channel X','#bf6932')]:ax.plot(t,[x[key] for x in part],label=label,color=color,marker='.',markersize=3)
   ax.set_ylabel('Consumed N');ax.set_xlabel('Simulation time / ms')
  else:ax.plot(t,[x['x'] for x in data],color='#159887',label='COM X − 501 m');ax.set_ylabel('World-coordinate extension / m')
  if mode!='forces':ax.set_xlabel('Simulation time / s')
  ax.set_title(scenario);ax.grid(alpha=.2);ax.legend(fontsize=8)
 fig.suptitle({'energy':'Measured native kinetic energy and supported storage','forces':'Actual consumed force and native correction: first 10 ms','motion':'Native movement after the constitutive transition'}[mode],fontsize=15)
 fig.savefig(media/(mode+'.png'),dpi=150);plt.close(fig)
# Copy an unmodified renderer image from the one-second removal run. Its missing beam is expected;
# numeric constitutive evidence comes from native records and the workbench, not screenshot pixels.
native_files=sorted((Path(selected['fracture-v1']['archivePath'])/'worker/config/screenshots').glob('*.png'))
assert len(native_files)>2;native=native_files[-2];shutil.copy2(native,media/'native-worker.png')
(media/'native-image-provenance.json').write_text(json.dumps(dict(source=str(native),attempt=selected['fracture-v1']['id'],sha256=hashlib.sha256(native.read_bytes()).hexdigest(),producer='RoR native renderer screenshot request; unmodified PNG'),indent=2),encoding='utf-8')
results=dict(schema=1,slice=5,branch='dev',build=build,nativeSourceFileCount=len(source['nativeSourceHashes']),sourceInventoryMatches=True,
 session=str(root),qualificationProfile='beam-transition-reference-v1',selected=summaries,checks=verified['checks'],uiChecks=ui['checks'],
 completedAttempts=11,retainedInitialFailedQualification='57da6d8386d141debd690db25f527d74',nativeExecutableSha256=build['sha256'],
 limitations=['Scoped native law/reference agreement, not calibrated material failure or dissipation','Tick-boundary net transitions, not each intermediate mutation','No new barrier/vehicle-science qualification','Observer overhead target remains unmet','No new video or Codex GPU-playback qualification'])
(report/'results.json').write_text(json.dumps(results,indent=2),encoding='utf-8');(repo/'doc/project/slices/slice-05-results.json').write_text(json.dumps(results,indent=2),encoding='utf-8')
def image(name,caption):return f'<figure><a href="{(media/name).as_uri()}"><img loading="lazy" src="{(media/name).as_uri()}" alt="{html.escape(caption)}"></a><figcaption>{html.escape(caption)}</figcaption></figure>'
rows=''.join(f'<tr><td>{s["scenario"]}</td><td>{s["event"]["tick"]}</td><td>{s["event"]["oldRestM"]:.6f} → {s["event"]["newRestM"]:.6f}</td><td>{s["event"]["oldStrengthN"]:.6f} → {s["event"]["newStrengthN"]:.6f}</td><td>{s["event"]["restStoragePortJ"]:.6f}</td><td>{s["event"]["removedStoragePortJ"]:.6f}</td><td>Passed</td></tr>' for s in summaries)
attempt_rows=''.join(f'<tr><td>{v["id"][:8]}</td><td>{v["definition"]["scenario"]}</td><td>{v["definition"]["durationSeconds"]}</td><td>{v["metrics"]["records"]:,}</td><td>{v["capture"]}</td><td>{v["validation"]}</td></tr>' for v in verified['runs'])
checks_rows=''.join(f'<tr><td>{html.escape(c["name"])}</td><td>{c["observed"]:.8g}</td><td>{c["limit"]:.8g}</td><td>{"Passed" if c["passed"] else "Failed"}</td></tr>' for c in summaries[0]['qualification']['checks'])
links=''.join(f'<li><a href="{f.as_uri()}">{html.escape(f.name)}</a></li>' for f in [report/'results.json',report/build['sourceRecord'],Path(build['nativeLog']),report/'transient-build-cleanup.json',root/'logs/contracts-final.log',ui_dir/'checks.json',sorted(report.glob('verification-05-*/checks.json'))[-1],root/'contract-final/native-reinspection.json'])
doc=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Slice 05 · Beam transition qualification</title>
<style>body{{margin:0;background:#edf2f3;color:#18313d;font:16px/1.6 system-ui,sans-serif}}main{{max-width:1120px;margin:auto;padding:44px 24px}}header{{background:#123745;color:white;padding:38px;border-radius:18px}}h1{{font-size:38px;line-height:1.15;margin:12px 0}}h2{{margin-top:42px;font-size:25px}}h3{{font-size:19px}}a{{color:#15716b}}header a{{color:#8fddd3}}.eyebrow{{font-size:12px;letter-spacing:.12em;text-transform:uppercase}}.cards,.grid{{display:grid;grid-template-columns:1fr 1fr;gap:20px}}.cards{{grid-template-columns:repeat(3,1fr);margin-top:24px}}.card,section{{background:white;border:1px solid #cfdddf;padding:22px;border-radius:12px;margin-top:20px}}.card strong{{display:block;font-size:28px;color:#15716b}}figure{{margin:22px 0}}img{{width:100%;height:auto;display:block;border:1px solid #ccdcdf;border-radius:9px}}figcaption{{font-size:13px;color:#53717b;margin-top:8px}}table{{border-collapse:collapse;width:100%;font-size:13px}}th,td{{padding:11px;text-align:left;border-bottom:1px solid #dbe5e7;white-space:nowrap}}.scroll{{overflow:auto}}code{{background:#edf4f4;padding:2px 5px;overflow-wrap:anywhere}}pre{{overflow:auto;background:#122f3a;color:#d9ecec;padding:20px;border-radius:10px}}.note{{border-left:4px solid #d99f4d;background:#fff8e9;padding:18px}}svg{{width:100%;height:auto}}footer{{margin:35px 0;color:#607e88;font-size:13px}}@media(max-width:650px){{main{{padding:20px 14px}}header{{padding:24px}}h1{{font-size:28px}}.grid,.cards{{grid-template-columns:1fr}}section{{padding:16px}}}}</style>
<main><header><div class="eyebrow">rigs-of-rods-trials · Slice 05 · 9 October 2026</div><h1>Beam transitions, proven through the native solver</h1><p>Actual tensile/compressive yield, strength changes and removal now have scoped reference qualification and a verified workbench ledger.</p><p>Development branch: <a href="https://github.com/bert-systems/rigs-of-rods-trials/tree/dev">dev</a>. Periodic promotion into master remains user-managed.</p></header>
<div class="cards"><div class="card"><strong>11 / 11</strong>New final-profile runs Complete / scoped Passed</div><div class="card"><strong>4 native paths</strong>Tension, compression, removal, cab guard</div><div class="card"><strong>~2 kHz</strong>Every-tick aggregate observation</div></div>
<h2>What this slice establishes</h2><p>Slice 04 captured controlled impacts but its 10 m/s matrix exercised parameter changes with no actual strength/removal changes. This slice isolates those missing native paths using pinned dry one-beam fixtures, adds strength-only aggregate events, checks an independent double-precision reference, and shows the signed storage ledger in React.</p>
<p class="note"><b>Scoped Passed means implementation and capture agree with these frozen native rules.</b> Physical material calibration, fracture dissipation, nonlinear vehicle closure and vehicle scientific acceptance remain unqualified. The existing observer-overhead target is still unmet. This slice did not repeat the large barrier matrix.</p>
<section><h3>Instrumentation and qualification flow</h3><svg viewBox="0 0 1000 150" role="img" aria-label="Native law to bounded archive to independent checks and workbench"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8" fill="#1f786e"/></marker></defs><g fill="#e5f2f0" stroke="#85bcb5"><rect x="5" y="25" width="220" height="95" rx="12"/><rect x="265" y="25" width="220" height="95" rx="12"/><rect x="525" y="25" width="220" height="95" rx="12"/><rect x="785" y="25" width="210" height="95" rx="12"/></g><g stroke="#1f786e" stroke-width="3" marker-end="url(#arrow)"><path d="M228 73h32"/><path d="M488 73h32"/><path d="M748 73h32"/></g><g fill="#163e45" text-anchor="middle" font-family="system-ui" font-size="15"><text x="115" y="58">Real native beam law</text><text x="115" y="84">Prime / kick / drift / solve</text><text x="375" y="58">Every-tick bounded ledger</text><text x="375" y="84">State, force epochs, ports</text><text x="635" y="58">CRC + independent reference</text><text x="635" y="84">Quality and scoped gates</text><text x="890" y="58">React archive inspector</text><text x="890" y="84">20-event pages + evidence</text></g></svg><p>Physics callbacks add no file I/O or dynamic allocation. The recorder writes existing 2,080-byte schema 2 records. Queries scan verified blocks and return bounded pages. Tick-boundary snapshots report net changes; intermediate mutations within a tick are not separately resolved.</p></section>
<h2>Measured transitions</h2><div class="scroll"><table><thead><tr><th>Fixture</th><th>Tick</th><th>Rest · m</th><th>Strength · N</th><th>Rest port · J</th><th>Removal port · J</th><th>Scope</th></tr></thead><tbody>{rows}</tbody></table></div>
<p>Each begins with 100 kg, k=10,000 N/m, rest=1 m, |extension|=0.05 m and zero velocity. Yield fixtures use ±200 N bounds, 2,000 N strength and plastic coefficient 0.25. Removal/guard fixtures use 200 N strength with high yield limits. Gravity, drag and ground contact are disabled. Three anchors are fixed; only beam 0 is active. The protected fixture sets a synthetic cab-node flag with one live beam to exercise the real protection branch; it has no cab contact surface.</p>
<p>All transitions occur in the initialization prime at tick 1. The observer compares the beginning/end state of that whole tick. Tensile rest change reduces modeled storage and strength; compression changes rest while preserving strength; removal removes active storage; strength-only protection changes strength without an elastic storage port.</p>
{image('energy.png','Plots from CRC-verified native records: kinetic energy and supported active linear storage, one-second runs.')}
{image('forces.png','Consumed elastic/correction channels and actual applied X force over the first 10 ms. For removal, correction cancels the elastic channel before integration.')}
{image('motion.png','Measured native COM movement. Float32 world-coordinate rounding is visible; plotted data are not synthetic trajectories.')}
<section><h3>Energy interpretation</h3><p>At the current beam length, the rest port is U(new rest/k) − U(old rest/k). Removal subtracts U(new rest/k). These ports explain model storage inventory changes without counting removed storage twice. A strength-only change contributes zero. The native elastic-force channel and correction channel remain separate, so the observed force and midpoint work can be reconstructed.</p><p>Lost supported storage is not a measurement of heat, crack formation, particulate energy, sound or material energy dispersal. No newly measured material-fracture energy is claimed. The new gate checks a 0.1 J core closure envelope alongside force, state, work, storage, port, identity and count checks.</p></section>
<h2>Feature evidence from the actual workbench</h2><p>Playwright operated the live coordinator on port 54325 and captured the following PNGs. Every row comes from a completed source-built attempt; page bounds, missing attempts, form defaults, desktop/mobile overflow and page errors were checked. The report uses ordinary images and does not depend on video decoding.</p><div class="grid">{''.join(image(s+'-ledger.png',s+' · actual verified archive ledger') for s in scenarios)}</div>
{image('qualification.png','The actual tensile fixture qualification panel, with observed discrepancies and frozen limits.')}
{image('native-worker.png','Unmodified OpenGL screenshot from the source-built removal fixture worker. Its active beam has been removed; numeric force/state evidence comes from the recorded physics, not this image.')}
<details><summary>Full desktop and mobile screenshots</summary>{image('dashboard-desktop.png','Actual workbench · desktop')}{image('dashboard-mobile.png','Actual workbench · mobile')}</details>
<h2>Checks and retained attempts</h2><div class="scroll"><table><thead><tr><th>ID</th><th>Scenario</th><th>Seconds</th><th>Records</th><th>Capture</th><th>Scoped validation</th></tr></thead><tbody>{attempt_rows}</tbody></table></div>
<p>The 0.2 s / 1 s pairs use different processes and exactly match over their first 400 state records, excluding observer timing and initialization-state bookkeeping ports. The three original analytical fixtures pass their existing acceptance limits. Native CTest: 1/1 ledger test; managed locked build: zero warnings/errors; contract checks include loss, CRC, bounded pages and final real-archive reinspection. Production React build passed.</p>
<p>Adversarial copies preserve valid CRCs while changing transition kind, storage port, event storage or force epoch. Capture remains Complete while the scientific gate fails, demonstrating that byte integrity alone cannot earn Passed. Original recorded files are preserved. All 12 retained native captures, including the initial qualification failure, were reinspected by the final reader.</p>
<details><summary>Representative tensile reference checks</summary><div class="scroll"><table><thead><tr><th>Check</th><th>Observed</th><th>Limit</th><th>Result</th></tr></thead><tbody>{checks_rows}</tbody></table></div></details>
<section><h3>Initial qualification failure, retained</h3><p>Attempt <code>57da6d8386d141debd690db25f527d74</code> completed native capture but failed the first acceptance candidate. The new checker read Y force as X, and consumed fields as generated fields, and its 10 µm world-position limit was below the float32 rounding scale near x=500 m. The checker offsets were corrected and the new position envelope explicitly frozen at 50 µm. The original result remains Failed; it was not overwritten. Final independent reinspection accepts its unchanged native data. Existing freefall/spring/damper limits were not relaxed.</p></section>
<h2>Build identity and reproduction</h2><p>Fresh VS 2022 x64 / MSVC 19.44 Release game outputs; CMake 3.31.10, Ninja 1.13.2, existing Conan 2.33 cache. Build source base: <code>{source['head']}</code> on dev with recorded implementation edits. All {len(source['nativeSourceHashes'])} native source hashes match the final checkout. Managed repairs were rebuilt separately; new producer byte layout is unchanged.</p><p>Native executable SHA-256: <code>{build['sha256']}</code>. Each private worker image/hash and loaded modules was verified. The installed root game was not used. Protected baseline executable identity remains separately checked before publication.</p>
<pre>.\\tools\\trials\\build.ps1 -Session &lt;unique-session&gt; -Parallel 6
.\\tools\\trials\\start.ps1 -Session &lt;unique-session&gt; -Port 54325 -Renderer OpenGL -EvidenceFrames
python tools/trials/verify-slice-05.py --session &lt;unique-session&gt;
python tools/trials/verify-slice-05-ui.py --session &lt;unique-session&gt;
dotnet run --project tests/trials/contracts-tests.csproj -c Release -- &lt;new-test-output&gt; &lt;session/archive&gt;</pre>
<p>Session: <code>{html.escape(str(root))}</code>. Its name is an identifier; actual build/run timestamps are in provenance records. To retain all captures within available storage, 0.65 GiB of this session's transient compiler object/PCH outputs was pruned after the successful fresh build. Executable/runtime, source records, logs, all prior sessions and all recorded originals remain. A later rebuild recreates those objects.</p><ul>{links}</ul>
<h2>Next gates</h2><p>Qualify later collision-induced yielding/removal, broader nonlinear/shock/hydro/rope storage, state mutation gateways, calibrated fracture dissipation, long/multiple impact windows and the still-unmet total observer overhead target. The downloaded vehicle/terrain collection, driven paths, gusts/particles and flight remain later work. Current vehicle scientific validation stays NotReady.</p>
<footer>Evidence is local and retained. A portable package contains raw fixture records, metadata, checks, frozen implementation files and images. Commits are pushed to dev; the user controls periodic dev-to-master pull requests.</footer></main></html>'''
(report/'index.html').write_text(doc,encoding='utf-8');(repo/'doc/project/reports/trial-slice-05-2026-10-09.html').write_text(doc,encoding='utf-8')
print(json.dumps(dict(report=str(report/'index.html'),nativeSha=build['sha256'],passed=len(verified['runs']),images=len(list(media.glob('*.png'))))))
