"""Dated Slice 04 report from real source-built archives and completed qualification checks."""
import argparse,json,html,statistics,shutil,math
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
p=argparse.ArgumentParser();p.add_argument('--session',required=True);p.add_argument('--repo',required=True);a=p.parse_args()
root=Path(a.session).resolve();repo=Path(a.repo).resolve();report=root/'report';plots=report/'plots';plots.mkdir(exist_ok=True)
def read(path):return json.loads(Path(path).read_text(encoding='utf-8-sig'))
def latest(pattern):return sorted(report.glob(pattern))[-1]
matrix=[r for path in report.glob('verification-04-matrix-*/checks.json') for r in read(path)['runs']]
assert len(matrix)==15 and all(r['capture']=='Complete' and r['metrics']['impactQualification']['status']=='Passed' for r in matrix)
checks={phase:read(latest(f'verification-04-{phase}-*/checks.json')) for phase in ['faults','controls','regression']}
assert len(checks['faults']['checks'])==3 and len(checks['controls']['checks'])==3 and len(checks['regression']['runs'])==3
ui=latest('ui-04-*/checks.json');assert all(v for k,v in read(ui)['checks'].items() if k!='browserErrors')
analysis=read(report/'analysis-04/checks.json');assert len(analysis['runs'])==15
canonical=read(report/'canonical-visual.json');visual=read(Path(canonical['archivePath'])/'result.json')
assert visual['capture']=='Complete' and visual['metrics']['impactQualification']['status']=='Passed'
media=root/'media'/'slice-04-native';assert read(media/'playback-check.json')['imageFallbackAdvances']
plt.rcParams.update({'figure.facecolor':'#f5f8fa','axes.facecolor':'white','font.size':11,'axes.spines.top':False,'axes.spines.right':False})
colors=['#177f89','#b36a27','#7047a2'];groups={v:[r for r in matrix if r['definition']['targetImpactSpeedMps']==v] for v in [3,5,10]}
series={v:read(report/'analysis-04'/(groups[v][0]['id']+'-series.json')) for v in groups}
fig,axs=plt.subplots(1,2,figsize=(12,4.8))
for (speed,rows),color in zip(series.items(),colors):
 trigger=groups[speed][0]['metrics']['impactDetail']['triggerTick'];dt=rows[0]['timeSeconds']/rows[0]['tick']
 t=np.array([(r['tick']-trigger)*dt for r in rows]);f=np.linalg.norm(np.array([r['netBarrierForceN'] for r in rows]),axis=1)/1e6
 for ax in axs:ax.plot(t,f,label=f'{speed} m/s target',color=color,lw=1.2)
axs[0].set_xlim(-2,4);axs[1].set_xlim(-.01,.15)
for ax in axs:ax.set_xlabel('Native time relative to first consumed contact / s');ax.set_ylabel('Net barrier force magnitude / MN');ax.grid(alpha=.2);ax.legend(fontsize=9)
axs[0].set_title('Required window: every retained 0.5 ms step');axs[1].set_title('Early contact detail: no display downsampling')
fig.tight_layout();fig.savefig(plots/'contact-force.png',dpi=180);plt.close(fig)
fig,axs=plt.subplots(1,2,figsize=(12,4.5));rows=series[10];trigger=groups[10][0]['metrics']['impactDetail']['triggerTick'];dt=rows[0]['timeSeconds']/rows[0]['tick'];t=np.array([(r['tick']-trigger)*dt for r in rows]);force=np.array([r['netBarrierForceN'] for r in rows]);imp=np.cumsum(force*dt,axis=0)/1000
for j,(label,color) in enumerate(zip(['World X','World Y','World Z'],colors)):axs[0].plot(t,imp[:,j],label=label,color=color)
axs[0].set_ylabel('Cumulative barrier impulse / kN s');axs[0].legend();axs[0].set_title('Actual applied contact increments integrated over dt')
axs[1].plot(t,[r['kineticJ']/1000 for r in rows],color=colors[2]);axs[1].set_ylabel('Movable-node kinetic energy / kJ');axs[1].set_title('10 m/s target: K is observed; dissipative closure unqualified')
for ax in axs:ax.set_xlabel('Native time relative to contact / s');ax.grid(alpha=.2)
fig.tight_layout();fig.savefig(plots/'impulse-energy.png',dpi=180);plt.close(fig)
fig,ax=plt.subplots(figsize=(10,4));detail=groups[10][0]['metrics']['impactDetail'];nodes=detail['nodePeakForceN'];ax.bar(list(nodes),[v/1e6 for v in nodes.values()],color=colors[0]);ax.set_xlabel('Stable pilot node ID');ax.set_ylabel('Peak individual barrier application / MN');ax.set_title('Observed nodal contact distribution: 10 m/s target');fig.tight_layout();fig.savefig(plots/'node-distribution.png',dpi=180);plt.close(fig)
summary=[]
for speed,rr in groups.items():
 d=rr[0]['metrics']['impactDetail'];approach=read(Path(rr[0]['archivePath'])/'approach.json')
 assert len(set(r['metrics']['impactDetail']['triggerTick'] for r in rr))==1
 assert len(set(read(Path(r['archivePath'])/'approach.json')['speedMps'] for r in rr))==1
 summary.append(dict(targetMps=speed,releaseMps=rr[0]['definition']['launchSpeedMps'],distanceM=rr[0]['definition']['barrierDistanceM'],approachMps=approach['speedMps'],triggerTick=d['triggerTick'],peakApplicationN=d['peakApplicationForceN'],peakNetN=d['peakNetBarrierForceN'],impulseNs=d['barrierImpulseNs'],midpointContactWorkJ=d['barrierWorkJ'],parameterTransitions=d['parameterTransitions'],strengthTransitions=d['strengthTransitions'],removedBeams=d['removedBeams'],repeats=len(rr),spreadPeakNetN=max(r['metrics']['impactDetail']['peakNetBarrierForceN'] for r in rr)-min(r['metrics']['impactDetail']['peakNetBarrierForceN'] for r in rr),spreadImpulseXNs=max(r['metrics']['impactDetail']['barrierImpulseNs'][0] for r in rr)-min(r['metrics']['impactDetail']['barrierImpulseNs'][0] for r in rr),stepMedianUsRange=[min(r['metrics']['performanceProbe']['medianUs'] for r in rr),max(r['metrics']['performanceProbe']['medianUs'] for r in rr)],workerWallSecondsRange=[min(r['metrics']['workerWallSeconds'] for r in rr),max(r['metrics']['workerWallSeconds'] for r in rr)]))
results=dict(slice=4,date='2026-10-09',base='5bfcb126270544e79f5410cc726648e884967ebd',branch='codex/trials-slice-04',session=str(root),nativeSha256=visual['executableSha256'],sourceInventory='source-20261009-015649-3790.json',contentCommit='34fefdd126784bf87b068fc283f812525d159dd7',matrix=summary,attemptIds=[r['id'] for r in matrix],operational={k:dict(checks=v['checks'],attempts=[dict(id=r['id'],execution=r['execution'],capture=r['capture'],validation=r['validation'],detail=r['metrics'].get('impactDetail')) for r in v['runs']]) for k,v in checks.items()},browser=read(ui),independentAnalysis=analysis,canonicalVisual=canonical,scientificScope='Approach and required capture qualified only. Vehicle scientific validation NotReady.',remaining=['Vehicle material/energy closure and fracture dissipation','Observer cost target and barrier off-mode equivalence','Long/multiple separated impact windows and larger/multi-actor workload','Driven journeys, atmosphere expansion and flight'])
(report/'results.json').write_text(json.dumps(results,indent=2),encoding='utf-8');(repo/'doc/project/slices/slice-04-results.json').write_text(json.dumps(results,indent=2),encoding='utf-8')
def link(path,label):return f'<a href="{html.escape(Path(path).resolve().as_uri(),quote=True)}">{html.escape(label)}</a>'
def image(path,alt):return f'<figure><img loading="lazy" src="{html.escape(Path(path).resolve().as_uri(),quote=True)}" alt="{html.escape(alt)}"><figcaption>{html.escape(alt)}</figcaption></figure>'
def table(headers,rows):return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+html.escape(str(v))+'</th>' for v in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+html.escape(str(v))+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
body=f'''<header><p class="eyebrow">RIGS OF RODS TRIALS · SLICE 04 · 9 OCTOBER 2026</p><h1>Controlled barriers.<br>Detailed physical impact capture.</h1><p>Source-built Daf Semi on Simple Test Terrain. Fifteen repeat-matrix runs passed the frozen approach and required capture profile. Raw node, beam and contact data now connects the native simulation to the trial workbench and archive inspector.</p><div class="badges"><span>15 / 15 approach + capture Passed</span><span>2 kHz required detail</span><span class="warn">Vehicle science: NotReady</span></div></header>
<nav><a href="#results">Matrix</a><a href="#pipeline">Pipeline</a><a href="#evidence">Native evidence</a><a href="#recovery">Faults & controls</a><a href="#limits">Costs & scope</a><a href="#reproduce">Reproduce</a></nav>
<section id="results"><h2>The controlled matrix is complete</h2><p>Five fresh private worker processes per target. Propulsion and braking are off after the settled rolling release; speed is not clamped during impact. Release speed compensates for measured approach losses. Target speed, acceptance limits and native contact law were not loosened.</p>'''
body+=table(['Target / m s⁻¹','Release / m s⁻¹','Barrier distance / m','Actual approach / m s⁻¹','First consumed tick','Peak individual / MN','Peak net / MN','Parameter changes'],[[s['targetMps'],s['releaseMps'],s['distanceM'],f"{s['approachMps']:.6f}",s['triggerTick'],f"{s['peakApplicationN']/1e6:.6f}",f"{s['peakNetN']/1e6:.6f}",s['parameterTransitions']] for s in summary])
body+='<p>All runs retained 12,001 contiguous detail frames, 176 nodes and 744 beams per frame, 2 s prehistory and 4 s posthistory inclusive. Required drop count is zero. Impact tick, approach speed, force peaks and impulse have zero observed spread across the five repeats at each target on this build. This is repeatability of this pinned native model, not evidence of real-world crash accuracy. No strength changes or beam removals occurred in this matrix; fracture-path qualification remains open.</p>'
body+=image(plots/'contact-force.png','Independent plots of actual 2 kHz native contact frames, including the early impact pulse.')+image(plots/'impulse-energy.png','World-space barrier impulse and observed movable-node kinetic energy; no fracture/dissipation acceptance implied.')+image(plots/'node-distribution.png','Stable node IDs identify the measured contact distribution.')+'</section>'
body+='''<section id="pipeline"><h2>From consumed force to inspectable evidence</h2><svg role="img" aria-label="Native physics to bounded capture to verified archive to coordinator and React" viewBox="0 0 1100 240"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#30b7ad"/></marker></defs><g fill="#172d3b" stroke="#345364"><rect x="10" y="50" width="195" height="125" rx="10"/><rect x="235" y="50" width="195" height="125" rx="10"/><rect x="460" y="50" width="195" height="125" rx="10"/><rect x="685" y="50" width="195" height="125" rx="10"/><rect x="910" y="50" width="180" height="125" rx="10"/></g><g fill="#e1edf4" font-family="system-ui" font-size="17" text-anchor="middle"><text x="107" y="83">Native force writes</text><text x="107" y="113">Before / after kick</text><text x="107" y="143">Nodes · beams · contact</text><text x="332" y="83">Preallocated queue</text><text x="332" y="113">Separate 2 s history</text><text x="332" y="143">First consumed trigger</text><text x="557" y="83">Recorder thread</text><text x="557" y="113">CRC + DONE + footer</text><text x="557" y="143">Durability / gap health</text><text x="782" y="83">.NET validation</text><text x="782" y="113">Peaks · impulse · index</text><text x="782" y="143">Independent quality</text><text x="1000" y="83">React workbench</text><text x="1000" y="113">Live envelopes</text><text x="1000" y="143">Archived tick inspector</text></g><g stroke="#30b7ad" stroke-width="3" marker-end="url(#arrow)"><path d="M205 112 H231"/><path d="M430 112 H456"/><path d="M655 112 H681"/><path d="M880 112 H906"/></g></svg><p>The observer records actual float accumulator increments beside the preserved solver operations. Terrain/object law output and applied increment remain distinct. Node snapshots follow the final attribution correction; beam snapshots preserve actual endpoint writes and before/after rest length, stiffness, strength and active flags. Normal/tangential decomposition, impulse and midpoint integration work are computed outside physics callbacks.</p><p>Physics callbacks perform no allocation, file/database/network access or UI waits. A preallocated queue feeds a recorder with separate rolling prehistory. Required loss stays sticky Incomplete while later observations continue. Execution Finalizing makes archive drainage visible. A CRC-verified index serves selected tick/node/beam data; missing ticks and invalid IDs are rejected. The 20 Hz display preserves maxima from all 200 Hz summary envelopes and flags gaps.</p>'''
body+=image(ui.parent/'impact-panel.png','Actual dashboard: separate peak definitions, vector impulse, required detail health and scoped approach gates.')+image(ui.parent/'tick-inspector.png','Archived native tick inspector: consumed node channels, beam endpoint writes and actual terrain/object applications.')
body+='<p>'+link(repo/'apps/trials/detail-format.md','Full binary layout, precision, trigger and resource contract')+'</p></section>'
body+='''<section id="evidence"><h2>The source-built scene, with playable images</h2><p>The native renderer supplied continuous PNGs from the new executable. FFmpeg encodes a nominal 2 fps sequence; media time is not a measurement clock. Ordinary-image playback is the primary proof path because earlier embedded videos went blank. Chrome pixel checks and image progression passed; Codex in-app GPU video playback remains unverified.</p>'''
native=sorted((media/'native-renderer-frames').glob('*.png'));assert len(native)>=8
for index in [len(native)//3,len(native)*2//3,len(native)-1]:body+=image(native[index],f'Actual native OpenGL frame {index+1} / {len(native)} · source-built barrier attempt {visual["id"][:8]}')
body+=f'<iframe title="Native renderer ordinary-image playback" src="{(media/"playback.html").as_uri()}" loading="lazy"></iframe><p>'+link(media/'playback.html','Open image player and WebM/MP4')+' · '+link(media/'playback-check.json','Visible-pixel and progression checks')+' · '+link(media/'native-renderer-frame-manifest.json','Native frame/executable provenance')+'</p></section>'
body+='<section id="recovery"><h2>Faults preserve evidence and independent progression</h2>'
operational=[r for v in checks.values() for r in v['runs']]
body+=table(['Attempt / scenario','Execution','Required capture','Science','Verified detail frames'],[[r['definition']['name'],r['execution'],r['capture'],r['validation'],(r['metrics'].get('impactDetail')or{}).get('records','analytical fixture')] for r in operational])
body+='''<p>Injected short-history, one refused queue admission, and a partial storage write all keep later native observations, retain gaps and prevent approach/capture acceptance. The storage fault exercises rollback of an incomplete DATA frame; it is not a physical disk-full test. Independent successor runs complete. Pause/resume is acknowledged at a native tick with a stationary clock. Cancellation retains a closed incomplete window. An abrupt verified-owned worker termination retains CRC-committed frames without a footer; its independent successor and explicitly requested fresh retry complete. The three existing dry free-fall/spring/damper fixtures still earn their unchanged scoped Passed.</p><p>Retained setup failures: the initial 768 MiB history proposal rejected the realized actor; a 256 MiB queue lost data on this archive drive; the 10 m/s release-speed spike missed its strict target. Resources and initial release conditions were revised with versioned profiles. Prototype captures preceded the final node-channel snapshot correction and are excluded from final qualification. A dashboard projection that omitted narrow maxima was corrected and checked against the raw peak.</p></section>'''
body+='<section id="limits"><h2>Measured costs and qualification limits</h2>'
body+=table(['Target / m s⁻¹','Released step median range / µs','Worker wall range / s','Peak net spread / N','Impulse X spread / N s'],[[s['targetMps'],' – '.join(f'{x:.1f}' for x in s['stepMedianUsRange']),' – '.join(f'{x:.1f}' for x in s['workerWallSecondsRange']),s['spreadPeakNetN'],s['spreadImpulseXNs']] for s in summary])
body+='''<p>Actual maximum frame stride is 205,056 bytes. The profile reserves 820,429,056 bytes of history (~782 MiB), a separate ~3 GiB queue and one scratch frame. Preflight requires 6 GiB available RAM, 3 GiB raw-data reservation and a 10 GiB free-disk floor, plus a writable storage probe. A six-second dense window is roughly 1.55 GB. This workload qualified zero loss using <code>daf-detail-resources-v2</code>; the earlier proposed buffer sizes did not.</p><p>The near-full archive volume is a ST2000DM008 spinning disk. Final durable writing can outlast physics. Worker wall includes loading, simulation, drain and verification; the recorded physics-finish wall event is polled at about 100 ms. The probe measures native step wall elapsed time, excludes its own sampling and is not CPU time. These runs do not establish the proposed observer overhead budget or barrier observation-off equivalence. Slice 03's coast full/off comparison is a different workload.</p><p>Independent streaming decoding verified CRC/DONE and reproduced all fifteen force peaks/impulses. Maximum float32 channel reconstruction error and momentum-kick residual are disclosed in the results JSON, rather than promoted to material-accuracy acceptance. This profile covers one pinned pilot and terrain/object contact applications. Cab/inter-actor contacts are not a qualified raw-contact stream. Longer runs, separated/retriggered windows, changed topology/cohorts, larger scenes, alternate renderers and physical disk exhaustion require further qualification.</p><p>Contact midpoint work is an integration contribution, not impact energy dissipated in concrete. Core linear storage remains a subset; nonlinear/shock/hydro terms, plastic/fracture dissipation, arbitrary state mutations and material calibration remain unqualified. Dense records can report strength/removal states, but this matrix did not exercise actual fracture. No force waveform faster than the 0.5 ms native step is resolved. Driven/path-controlled approaches, atmosphere expansion and flight remain later work.</p></section>'''
build=read(report/'build-20261009-015649-3790.json')
body+=f'''<section id="reproduce"><h2>Build identity and reproduction</h2><p>Fork: {link(repo/'PROJECT.md','bert-systems/rigs-of-rods-trials')} · base <code>5bfcb126270544e79f5410cc726648e884967ebd</code> · content <code>34fefdd126784bf87b068fc283f812525d159dd7</code>. VS2022/MSVC19.44 x64 Release, CMake3.31.10, Conan2.33, Ninja1.13.2, .NET10.0.203, Node22.15. A fresh session native build reused cached dependencies; subsequent fixes were incrementally rebuilt at six compiler jobs. Standalone CTest (one test), locked managed build, archive contracts and React production build passed. The original baseline and installed runtime remain untouched.</p><p>Native executable SHA-256:<br><code>{visual['executableSha256']}</code></p><p>Every attempt records its exact private executable/process path, loaded modules, inputs and asset hashes. Required final evidence uses this native identity. Publication details are added after commit/merge/push.</p><pre>tools/trials/build.ps1 -Session &lt;new-session&gt; -Parallel 6
tools/trials/start.ps1 -Session &lt;new-session&gt; -Port 54324 -Renderer OpenGL
python tools/trials/verify-slice-04.py --session &lt;new-session&gt; --phase matrix --speed 3 --release 3.8
python tools/trials/verify-slice-04.py --session &lt;new-session&gt; --phase matrix --speed 5 --release 6.2
python tools/trials/verify-slice-04.py --session &lt;new-session&gt; --phase matrix --speed 10 --release 12.25
# Restart the owned coordinator with -EvidenceFrames for visual/control checks.
python tools/trials/verify-slice-04.py --session &lt;new-session&gt; --phase faults --release 6.2
python tools/trials/verify-slice-04.py --session &lt;new-session&gt; --phase controls --release 6.2
python tools/trials/verify-slice-04.py --session &lt;new-session&gt; --phase regression
python tools/trials/analyze-slice-04.py --session &lt;new-session&gt;</pre>'''
body+='<p>'+ ' · '.join([link(report/'results.json','Measured results'),link(report/build['sourceRecord'],'Exact native source hashes'),link(report/'build-20261009-015649-3790.json','Build record'),link(root/'logs/native-20261009-015649-3790.log','Native build log'),link(root/'logs/managed-final-build.log','Managed build'),link(root/'logs/contracts-final.log','Archive contracts'),link(report/'analysis-04/checks.json','Independent analysis'),link(report/'publication.json','Publication verification'),link(report/'bundle-check.json','Portable bundle verification'),link(report/'slice-04-evidence.zip','Portable evidence ZIP')])+'</p><p>The portable bundle includes all attempt metadata/logs, UI/native media, charts and one representative complete raw impact window. Other full raw windows remain retained in the session archive with SHA-256 inventory; binaries and dependency caches are not bundled. '+link(repo/'apps/trials/README.md','Runbook')+'</p></section>'
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#0c1822;color:#dce9ef;font:16px/1.6 system-ui}header,section,nav{max-width:1140px;margin:auto;padding:35px 28px}header{padding-top:65px}h1{font-size:clamp(32px,5vw,58px);line-height:1.12;margin:14px 0 25px}h2{font-size:29px;margin:0 0 20px}p{color:#b8cbd5}.eyebrow{font-size:13px;letter-spacing:2px;color:#47c9bc}a{color:#66d2c7;overflow-wrap:anywhere}nav{display:flex;flex-wrap:wrap;gap:22px;border-block:1px solid #304351;padding-block:20px}section{border-bottom:1px solid #304351}.badges{display:flex;flex-wrap:wrap;gap:12px}.badges span{padding:8px 14px;border:1px solid #257f77;border-radius:25px;background:#173b3c}.badges .warn{border-color:#ac7831;background:#443621;color:#ffd799}figure{margin:25px 0}img{max-width:100%;height:auto;border-radius:9px;border:1px solid #304b5e}figcaption{font-size:14px;color:#a8bdc9;padding-top:6px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:12px;text-align:left;border-bottom:1px solid #304351}th{color:#8fbdcf}.scroll{overflow-x:auto}svg{width:100%;min-height:140px}iframe{border:1px solid #304b5e;width:100%;height:830px;border-radius:10px}code{font-size:13px;overflow-wrap:anywhere}pre{overflow-x:auto;padding:20px;background:#122633;border-radius:9px;font:13px/1.7 monospace}@media(max-width:600px){header,section,nav{padding-inline:18px}iframe{height:580px}h2{font-size:24px}}'''
page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Slice 04 · controlled barrier and detailed impact</title><style>'+css+'</style></head><body>'+body+'</body></html>'
(report/'index.html').write_text(page,encoding='utf-8');(repo/'doc/project/reports/trial-slice-04-2026-10-09.html').write_text(page,encoding='utf-8')
print(json.dumps(dict(report=str(report/'index.html'),matrixRuns=len(matrix),operationalRuns=len(operational),nativeFrames=len(native))))
