"""Generate a source-build evidence report from recorded, real trial artifacts."""
import argparse,json,html,os,math,urllib.parse
from pathlib import Path
parser=argparse.ArgumentParser()
parser.add_argument('--session',required=True)
parser.add_argument('--repo',default=str(Path(__file__).resolve().parents[2]))
args=parser.parse_args()
session=Path(args.session).resolve();repo=Path(args.repo).resolve()
verification=Path((session/'report/latest-verification.txt').read_text(encoding='utf-8').strip())
checks=json.loads((verification/'checks.json').read_text(encoding='utf-8'))
assert checks['allBooleanChecksPass']
runs=checks['attempts'];pilot=runs[0]
pilot_dir=Path(pilot['archivePath'])
samples=[json.loads(line) for line in (pilot_dir/'summaries.jsonl').read_text(encoding='utf-8').splitlines()]
coast=[s for s in samples if s['phase']=='coast']
delta=[coast[-1]['centerM'][i]-coast[0]['centerM'][i] for i in range(3)]
distance=math.sqrt(sum(d*d for d in delta))
source_records=sorted((session/'report').glob('source-*.json'))
source=json.loads(source_records[-1].read_text(encoding='utf-8-sig')) if source_records else {}
build_records=sorted((session/'report').glob('build-*.json'))
build=json.loads(build_records[-1].read_text(encoding='utf-8-sig')) if build_records else {}
esc=lambda s:html.escape(str(s))
def chart(field,label,unit):
 points=samples[::max(1,len(samples)//400)]
 lo=min(0,min(s[field] for s in points));hi=max(0,max(s[field] for s in points));hi=hi if hi!=lo else lo+1;span=hi-lo
 path=' '.join(('M' if i==0 else 'L')+str(round(35+(s['timeSeconds']-points[0]['timeSeconds'])/(points[-1]['timeSeconds']-points[0]['timeSeconds'])*850,2))+','+str(round(200-(s[field]-lo)/span*160,2)) for i,s in enumerate(points))
 return '<figure class="plot"><figcaption>'+esc(label)+' · '+unit+'</figcaption><svg viewBox="0 0 920 240" role="img" aria-label="'+esc(label)+' from actual native summaries"><path d="M35 40V200H885" fill="none" stroke="#bccad0"/><path d="'+path+'" fill="none" stroke="#087f78" stroke-width="2"/><text x="35" y="228">0 s</text><text x="800" y="228">'+str(round(points[-1]['timeSeconds'],2))+' s</text><text x="40" y="28">'+esc(format(hi,'.5g'))+' '+unit+'</text></svg></figure>'
rows=''.join('<tr><td>'+esc(a['definition']['name'])+'<small>'+a['id'][:12]+'</small></td><td>'+a['execution']+'</td><td>'+a['capture']+'</td><td>'+str(a['metrics']['records'])+'</td><td>'+str(a['metrics']['dropped'])+'</td><td>'+str(a['processId'])+'</td><td>'+a['validation']+'</td></tr>' for a in runs)
checkrows=''.join('<tr><td>'+esc(k)+'</td><td class="pass">PASS</td></tr>' for k,v in checks.items() if isinstance(v,bool))
diagram='''<svg viewBox="0 0 980 220" role="img" aria-label="Implemented trial data flow">
<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="#087f78"/></marker></defs>
<g fill="#edf6f4" stroke="#8fc4ba"><rect x="5" y="25" width="210" height="90" rx="10"/><rect x="255" y="25" width="210" height="90" rx="10"/><rect x="505" y="25" width="210" height="90" rx="10"/><rect x="755" y="25" width="210" height="90" rx="10"/></g>
<g font-size="17" text-anchor="middle" fill="#163641"><text x="110" y="60">React workbench</text><text x="360" y="60">.NET coordinator</text><text x="610" y="60">Source-built RoR</text><text x="860" y="60">Native writer</text></g>
<g font-size="13" text-anchor="middle" fill="#4d6771"><text x="110" y="87">Typed setup / live charts</text><text x="360" y="87">Queue / profiles / SQLite</text><text x="610" y="87">Integration observer</text><text x="860" y="87">CRC archive / summaries</text></g>
<g stroke="#087f78" stroke-width="2" fill="none" marker-end="url(#arrow)"><path d="M215 65H250"/><path d="M465 65H500"/><path d="M715 65H750"/><path d="M860 120V170H360V120"/><path d="M360 190H110V120"/></g>
<g font-size="12" fill="#4d6771"><text x="460" y="160">Durable capture and reduced summaries</text><text x="110" y="212">Independent native clock + applied command ticks</text></g></svg>'''
css='''*{box-sizing:border-box}body{margin:0;background:#f5f4ef;color:#16313c;font:16px/1.65 system-ui,sans-serif}header{background:#102e39;color:#f4f6f1;padding:58px max(5vw,24px)}header>div,main{max-width:1180px;margin:auto}h1{font-size:clamp(34px,5vw,62px);line-height:1.1;letter-spacing:-2px;margin:16px 0}h2{font-size:29px;line-height:1.3}h3{font-size:20px}p{max-width:95ch}a{color:#077c74}header a{color:#86ded0}.eyebrow{font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#7ddccd}.lede{font-size:21px;color:#d3e4e8;max-width:850px}.badge{display:inline-block;background:#1d524f;color:#a7efe1;border-radius:20px;padding:6px 13px;font-size:13px;margin:8px 5px 0 0}.badge.amber{background:#574923;color:#ffe4a1}main{padding:22px 24px 70px}section{padding:26px 0;border-bottom:1px solid #d5dedc}nav{display:flex;gap:20px;flex-wrap:wrap;padding:15px 0;font-size:14px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.card{background:white;border:1px solid #d8e3df;border-radius:10px;padding:20px}.card strong{display:block;font-size:28px}.card span,small{display:block;font-size:12px;color:#647b83}.two{display:grid;grid-template-columns:1fr 1fr;gap:22px}.notice{border-left:4px solid #c69129;background:#fff3d7;padding:18px 22px;margin:20px 0}.pass{color:#08796e;font-weight:650}figure{margin:20px 0}img,video{max-width:100%;display:block;border-radius:10px;border:1px solid #a6bdbd}figcaption{font-size:13px;color:#526a75;margin:8px 0}.screen{width:100%}code{font-size:13px;overflow-wrap:anywhere;background:#e8efec;padding:2px 5px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#15313c;color:#e0f1ee;padding:20px;border-radius:10px;font-size:13px}pre code{background:none;color:inherit;padding:0}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px;background:white}th,td{padding:12px;text-align:left;border-bottom:1px solid #d9e3df;vertical-align:top}th{background:#e7efec}.plot{padding:16px;background:white;border:1px solid #d6e1dc;border-radius:10px}.plot svg,section>svg{width:100%;height:auto}.plot text{font:12px system-ui;fill:#596f76}details{padding:14px;background:#e9efea;border-radius:10px;margin:12px 0}summary{cursor:pointer;font-weight:600}.hash{font:12px monospace;overflow-wrap:anywhere}footer{color:#667d82;padding:25px 0;font-size:13px}@media(max-width:760px){header{padding:35px 22px}main{padding:12px 18px 40px}.cards{grid-template-columns:1fr 1fr}.two{grid-template-columns:1fr}th,td{padding:9px}h2{font-size:25px}}'''
template=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RoR Trials — Slice 01 implementation evidence</title><style>__CSS__</style></head><body>
<header><div><div class="eyebrow">rigs-of-rods-trials · implementation evidence · 2026-10-08</div><h1>A working trial foundation.</h1><p class="lede">A source-built simulation, native measurements, isolated trial execution and a live React workbench — exercised together on the verified Windows workstation.</p><span class="badge">Slice 01 feature checks passed</span><span class="badge">Real source-built workers</span><span class="badge amber">Scientific validation: NotReady</span></div></header>
<main><nav aria-label="Report sections"><a href="#delivery">Delivery</a><a href="#proof">Simulation proof</a><a href="#measure">Measurements</a><a href="#qa">Checks</a><a href="#provenance">Provenance</a><a href="#limits">Next slices</a></nav>
<section id="delivery"><h2>What this slice completes</h2>
<div class="cards"><div class="card"><strong>~2 kHz</strong><span>Native aggregate archive</span></div><div class="card"><strong>~200 Hz</strong><span>Reduced native summaries</span></div><div class="card"><strong>__RECORDS__</strong><span>Verified primary tick records</span></div><div class="card"><strong>0</strong><span>Primary required records lost</span></div></div>
<p>The workbench defines an immutable Daf Semi / Simple Test Terrain coast experiment, launches a fresh private worker for each repeat, displays live force/momentum/energy and environmental values, and retains independently reported execution, capture and scientific quality. Pause/resume applies at a synchronized native tick. Cancel retains partial results; manual retry creates a new attempt; archive marks retain files.</p>
__DIAGRAM__
<div class="notice"><strong>Measurement coverage is intentionally visible.</strong> These are every-step <em>aggregate</em> observations and integration-boundary accounting. Full force-model attribution, conservative/dissipative energy closure, qualified impact outcomes and detailed node/beam/contact windows remain unfinished. Complete capture is separate from scientific acceptance.</div>
</section>
<section id="proof"><h2>Actual simulation and workbench</h2>
<figure><img class="screen" src="__MEDIA__/workbench-running.png" alt="Live React workbench showing a source-built coast trial and real native measurements"><figcaption>Playwright screenshot of the running workbench. Values come from the source-built worker's native observer; the UI does not generate physics samples.</figcaption></figure>
<div class="two"><figure><img src="__MEDIA__/native-coast-1.png" alt="Daf Semi in the source-built simulation during settling"><figcaption>Native RoR screenshot during settling. Private trial overlay identifies the source-built worker and incomplete scientific coverage.</figcaption></figure><figure><img src="__MEDIA__/native-coast-2.png" alt="Source-built Daf Semi coasting with nonzero wheel speed"><figcaption>Native RoR screenshot after rolling release. The wheel-speed overlay and speedometer show motion. Recorded COM displacement over the coast is __DISTANCE__ m.</figcaption></figure></div>
<figure><video controls preload="metadata" poster="__MEDIA__/native-coast-2.png"><source src="__MEDIA__/native-coast.mp4" type="video/mp4"></video><figcaption>FFmpeg gdigrab capture of the actual RoR window, H.264 MP4. Playwright verifies the report and video playback; FFmpeg records the native scene.</figcaption></figure>
<div class="two"><figure><img src="__MEDIA__/workbench-paused.png" alt="Trial paused with retained measurements"><figcaption>Native clock stopped at tick __PAUSE__; pause and resume acknowledge the same tick. Recorder publication has its own lag and does not advance the physical clock.</figcaption></figure><figure><img src="__MEDIA__/workbench-result.png" alt="Completed capture with scientific validation NotReady"><figcaption>Execution completed, required capture complete, scientific validation NotReady. The independent states prevent an execution success from implying scientific acceptance.</figcaption></figure></div>
</section>
<section id="measure"><h2>Recorded quantities and their interpretation</h2>
<p>For the movable-node cohort, the observer records mass-weighted center, momentum, kinetic energy, total force actually consumed at the velocity update and the added ground/object-contact force. It measures kinetic work using midpoint velocity at that same update boundary. World axes are native Y-up; units are SI.</p>
<pre>p = Σ m v                         K = ½ Σ m |v|²
rₚ = Σ [m(v_after − v_before) − F_consumed Δt]
W_update = Σ F_consumed · ½(v_before + v_after) Δt
rₖ = Σ [K_after − K_before − W_update]</pre>
<p>The observed mass is __MASS__ kg. The primary run's maximum momentum-update residual is __PRES__ kg·m/s and maximum kinetic-work-update residual is __WRES__ J. These small residuals confirm consistency at the numerical update boundary; they do not establish closed energy accounting across springs, damping, friction, plasticity, breaking, propulsion or fluid/aerodynamic models.</p>
__PLOTS__
<p>These plots use recorded native summaries, reduced only for rendering. Release is a marked initialization boundary, with body/wheel velocity set coherently after settling. The archive remains authoritative for every recorded tick. Live chart samples are a reduced projection and do not preserve every component peak.</p>
<details><summary>Environment behavior</summary><p>Trials configure negative scalar gravity, explicit air density and a constant world-space wind. The pilot's existing generic drag path uses air-relative velocity and density scaling; its legacy stochastic draws are retained. Dry-air temperature and derived pressure are recorded state metadata, without thermal exchange. Other aerodynamic models, gusts and particulate interactions are future work. Changed-environment repeats verified native values −8 m/s², 1 kg/m³ and wind [3, 0, −1] m/s; that is an adoption check, not an atmospheric-model calibration.</p></details>
</section>
<section id="qa"><h2>Feature completion checks</h2>
<div class="table-wrap"><table><thead><tr><th>Recorded check</th><th>Result</th></tr></thead><tbody>__CHECKROWS__</tbody></table></div>
<p>The automated native ledger suite checks an independent impulse/work example, mass-weighted center, detectable state-mutation residual, invalid/nonfinite input and a standard CRC vector. The coordinator checks configuration bounds, SQLite recovery, archive CRC corruption and verified-prefix recovery after a truncated footer. The standalone ledger suite has one registered CTest; the original game did not acquire a broad automated physics qualification suite.</p>
<h3>Six real worker attempts in the final feature check</h3>
<div class="table-wrap"><table><thead><tr><th>Study / attempt</th><th>Execution</th><th>Capture</th><th>Records</th><th>Lost</th><th>PID</th><th>Validation</th></tr></thead><tbody>__RUNROWS__</tbody></table></div>
<p>Each attempt has a different private runtime/profile and retained archive. The two wind repeats share one immutable revision. The cancelled attempt preserves a clean partial archive; its execution is Cancelled and it cannot represent a completed study. The next independent attempt runs, and retry creates a separate attempt. The workbench was checked at 1600×1050 and 390×844 without page errors or page-level overflow.</p>
<details><summary>Preserved failures and corrections</summary><ul><li>The first source build exposed the fork's custom ActorPtr dereference requirement; using GetRef() fixed compilation.</li><li>The first host startup exposed ASP.NET web-root setup ordering; the root is now passed at builder creation.</li><li>An early writer design lost 3,251 required records under pressure. That attempt remains Completed / Incomplete / NotReady in the archive. The bounded queue was enlarged and durable writes grouped. Final feature attempts have zero dropped records; broad stress and filesystem-failure qualification remain pending.</li><li>An early pause assertion read delayed recorder samples. Native event ticks proved the pause; an independent native clock now drives the display and the check.</li><li>Evidence tooling needed selectors that account for continuous polling and navigation-arrow text. Failed logs remain preserved. A build command used a restore-only flag before correction to the MSBuild RestoreLockedMode property.</li></ul></details>
</section>
<section id="provenance"><h2>Source build and evidence provenance</h2>
<p>Repository: <a href="https://github.com/bert-systems/rigs-of-rods-trials">bert-systems/rigs-of-rods-trials</a>, forked from <a href="https://github.com/RigsOfRods/rigs-of-rods">RigsOfRods/rigs-of-rods</a>. This slice began at __HEAD__, with content pinned to __CONTENT__. Compilation occurred on the implementation branch with an explicitly recorded dirty source tree. The source inventory and tracked patch bind these outputs to the implementation; publication identifiers are recorded separately after merge/push.</p>
<div class="table-wrap"><table><tbody><tr><th>New executable</th><td class="hash">__EXE__</td></tr><tr><th>SHA-256</th><td class="hash">__SHA__</td></tr><tr><th>Compiler / build</th><td>VS 2022 x64 / MSVC 19.44; CMake 3.31.10; Ninja 1.13.2; Conan 2.33.0; Release</td></tr><tr><th>Web stack</th><td>.NET SDK 10.0.203; React 19.3.0; Vite 8.3.4; Node 22.15.0; locked dependency files</td></tr><tr><th>Evidence root</th><td class="hash">__SESSION__</td></tr></tbody></table></div>
<p>The game was configured in a new native build directory and compiled from source. Later fixes used incremental rebuilding. The existing Conan dependency cache was reused; this is not a fresh dependency-cache qualification. Workers copy the newly compiled runtime and pin vehicle/terrain package hashes. Observed process paths and loaded module lists are saved per attempt. Installed game executables and DLLs in the workspace parent do not supply this proof. Original source-build evidence remains preserved.</p>
<p><a href="__MEDIA__/checks.json">Full final feature-check JSON</a> · <a href="__REPORT__/__SOURCE_RECORD__">Source inventory</a> · <a href="__REPORT__/__BUILD_RECORD__">Build record</a> · <a href="__ARCHIVE__/__ID__/manifest.json">Primary manifest</a> · <a href="__ARCHIVE__/__ID__/process-provenance.json">Observed process/modules</a> · <a href="__ARCHIVE__/__ID__/result.json">Primary result</a> · <a href="__ARCHIVE__/__ID__/steps.rort">Binary capture</a> · <a href="__REPORT__/publication.json">Commit / merge / push record</a></p>
<h3>Repeat this session</h3><pre>From D:\Rigs of Rods\rigs-of-rods-trials (PowerShell):
$trialSession='D:\Rigs of Rods\trial-slice-01-new-session'
.\tools\trials\build.ps1 -Session $trialSession
.\tools\trials\start.ps1 -Session $trialSession
# Open http://127.0.0.1:54321/
# Run tools/trials/verify-workbench.py --session $trialSession
# See apps/trials/README.md for tool paths and prerequisites.</pre>
</section>
<section id="limits"><h2>Next major slices</h2><div class="two"><div><h3>Slice 02 · accounting and fixtures</h3><p>Explicit generated/consumed force channels; gravity, drag, spring/damper and contact work; initialization and mass/state ports; closed core energy balance; real native analytical fixtures; performance/repeatability measurements; scoped acceptance thresholds.</p></div><div><h3>Slice 03 · controlled impacts</h3><p>Pinned barrier/vehicle placement; verified speed/alignment and trigger; impact outcomes; deformation/breakage transitions; required node/beam/contact pre/post event windows; live impact diagnostics and scoped validation.</p></div></div>
<p>Current trial capability is restricted to the pinned single-actor coast study and this workstation's windowed Direct3D9 profile. There is no generalized journey authoring, aircraft qualification, environmental field/gust system, scientific 3D inspector or calibrated energy-dispersal model yet. Storage/orphan/crash/fault/performance stress cases need further qualification. The first slice establishes a functioning end-to-end foundation for that work.</p></section>
<footer>Images: Playwright workbench capture and native RoR screenshot requests. Video: FFmpeg native-window capture. Charts: actual archived native summaries. Large evidence stays outside Git; repository documents and code are committed together. <a href="https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/">SQLite/.NET documentation</a> · <a href="https://react.dev/learn">React documentation</a></footer></main></body></html>'''
values={'CSS':css,'RECORDS':pilot['metrics']['records'],'DIAGRAM':diagram,'DISTANCE':f'{distance:.3f}','PAUSE':checks['pausedTick'],
 'MASS':f"{coast[-1]['massKg']:.3f}",'PRES':f"{pilot['metrics']['maxMomentumUpdateResidualKgMps']:.8g}",'WRES':f"{pilot['metrics']['maxKineticWorkResidualJ']:.8g}",
 'PLOTS':chart('kineticJ','Movable-node kinetic energy','J')+chart('workResidualJ','Kinetic-work update residual','J'),
 'CHECKROWS':checkrows,'RUNROWS':rows,'HEAD':source.get('head','e85535569102b6251849af574026984e3213b3f4'),
 'CONTENT':source.get('content','34fefdd126784bf87b068fc283f812525d159dd7'),'EXE':build.get('exe',''),'SHA':pilot['executableSha256'],
 'SESSION':session,'SOURCE_RECORD':source_records[-1].name if source_records else '', 'BUILD_RECORD':build_records[-1].name if build_records else '',
 'ID':pilot['id']}
for key,value in values.items():template=template.replace('__'+key+'__',esc(value) if key not in ('CSS','DIAGRAM','PLOTS','CHECKROWS','RUNROWS') else str(value))
for destination in [session/'report/index.html',repo/'doc/project/reports/trial-slice-01-2026-10-08.html']:
 result=template
 for key,path in [('MEDIA',verification),('REPORT',session/'report'),('ARCHIVE',session/'archive')]:
  relative=os.path.relpath(path,destination.parent).replace('\\','/')
  result=result.replace('__'+key+'__',urllib.parse.quote(relative,safe='/'))
 destination.write_text(result,encoding='utf-8')
summary={'schema':1,'slice':'01','sourceHeadAtBuild':source.get('head'),'content':source.get('content'),'exeSha256':pilot['executableSha256'],
 'evidenceRoot':str(session),'featureCheck':str(verification/'checks.json'),'allFeatureBooleansPass':checks['allBooleanChecksPass'],
 'primaryRecords':pilot['metrics']['records'],'primaryDropped':pilot['metrics']['dropped'],'primaryCoastDisplacementM':distance,
 'nativePauseTick':checks['pausedTick'],'scientificValidation':'NotReady','attempts':runs,
 'unqualified':['full force/energy attribution','analytical engine fixtures','barrier outcomes','raw node/beam/contact event windows','operational fault/performance stress']}
(repo/'doc/project/slices/slice-01-results.json').write_text(json.dumps(summary,indent=2),encoding='utf-8')
print(json.dumps({'report':str(session/'report/index.html'),'repositoryReport':str(repo/'doc/project/reports/trial-slice-01-2026-10-08.html'),'verifiedRecords':pilot['metrics']['records'],'coastDisplacementM':distance},indent=2))
