"""Publish measured Slice06 HTML, native plots and source-input verification."""
import argparse,json,time,hashlib,html,shutil,struct,zlib,statistics
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
p=argparse.ArgumentParser();p.add_argument('--session',required=True);p.add_argument('--repo',required=True);a=p.parse_args()
root=Path(a.session).resolve();repo=Path(a.repo).resolve();report=root/'report';media=report/'media'/'slice-06';media.mkdir(parents=True,exist_ok=True)
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
resultPath=sorted(report.glob('analysis-06-*/results.json'))[-1];r=read(resultPath)
base=read(sorted(report.glob('verification-06-baseline-*/checks.json'))[-1]);final=read(sorted(report.glob('verification-06-optimized-*/checks.json'))[-1]);cadence=read(sorted(report.glob('verification-06-cadence-d-*/checks.json'))[-1]);visual=read(sorted(report.glob('verification-06-visual-*/checks.json'))[-1])
buildPath=sorted(report.glob('build-*.json'))[-1];build=read(buildPath);sourcePath=report/build['sourceRecord'];source=read(sourcePath)
inputs=source['nativeSourceHashes'];wrong=[k for k,v in inputs.items() if hashlib.sha256((repo/k).read_bytes()).hexdigest().upper()!=v]
assert not wrong,wrong
assert hashlib.sha256((root/'build/bin/RoR.exe').read_bytes()).hexdigest().upper()==r['optimizedSha256']==build['sha256']
uiPath=sorted(report.glob('ui-06-*/checks.json'))[-1];ui=read(uiPath);assert all(ui['checks'].values())
for path in uiPath.parent.glob('*.png'):shutil.copy2(path,media/path.name)
oldUI=sorted(report.glob('ui-06-*/checks.json'))[0]
shutil.copy2(oldUI.parent/'finalizing-recorder.png',media/'prototype-d-draining.png')
v=visual['runs'][0];frames=sorted((Path(v['archivePath'])/'worker/config/screenshots').glob('*.png'))
assert len(frames)>=8
for name,index in [('native-before.png',0),('native-impact.png',len(frames)//2),('native-after.png',-1)]:shutil.copy2(frames[index],media/name)
plt.rcParams.update({'font.family':'DejaVu Sans','font.size':10,'figure.facecolor':'#101e2b','axes.facecolor':'#101e2b','text.color':'#e2eef6','axes.labelcolor':'#bfcedb','axes.edgecolor':'#60788b','xtick.color':'#bfcedb','ytick.color':'#bfcedb','grid.color':'#354958','savefig.facecolor':'#101e2b'})
def save(fig,name):fig.tight_layout(pad=1.8);fig.savefig(media/name,dpi=160);plt.close(fig)
fig,ax=plt.subplots(figsize=(10,4));colors=['#7399c1','#52c9b9'];labels=[];values=[]
for title,key in [('Baseline · D:','baseline'),('Prototype · D:','prototypeSameDrive'),('Final · C:','optimized')]:
 for mode in ['off','full']:labels.append(title+'\n'+mode);values.append(r['timings'][key][mode]['medianOfMediansUs'])
bars=ax.bar(range(6),values,color=colors*3);ax.set_xticks(range(6),labels);ax.set_ylabel('Step wall elapsed · µs');ax.set_ylim(0,90);ax.grid(axis='y',alpha=.3)
for b,val in zip(bars,values):ax.text(b.get_x()+b.get_width()/2,val+1.5,f'{val:.1f}',ha='center')
ax.set_title('Three fresh-process repeats per mode; final C: is a separate volume');save(fig,'performance.png')
profile=r['phaseProfile'];labels=['Energy before','Detail before (inactive)','Solver + force attribution','Energy after + detail','Ledger finalize / queue'];values=[v['sumWallUs']/profile['steps'] for v in profile['phases']]
fig,ax=plt.subplots(figsize=(10,3.8));ax.barh(labels,values,color='#52c9b9');ax.invert_yaxis();ax.set_xlabel('Mean wall elapsed · µs per step');ax.grid(axis='x',alpha=.3);ax.set_title('Opt-in coast diagnostic: clock overhead included');save(fig,'phases.png')
dv=cadence['runs'][0];samples=cadence['live'][dv['id']];samples=[s for s in samples if (s['detailProgress'].get('recorder') or s['workerStatus'].get('recorders',{}).get('detail'))]
t0=samples[0]['wall'];xx=[s['wall']-t0 for s in samples];hs=[(s.get('recorderHealth') or {}).get('detail') or s['detailProgress'].get('recorder') or s['workerStatus']['recorders']['detail'] for s in samples]
# Earlier collector revisions retained the last writer progress snapshot at
# terminal state. Use the independently published terminal health for that point.
hs[-1]=dv['recorderHealth']['detail']
fig,axes=plt.subplots(2,1,figsize=(10,5),sharex=True);axes[0].step(xx,[s['queued']/s['capacity']*100 for s in hs],where='post',color='#f7bc6a');axes[0].axhline(80,color='#b67876',ls='--',label='80% UI warning');axes[0].set_ylabel('Queue occupied · %');axes[0].legend(loc='upper left')
axes[1].step(xx,[s['durable'] for s in hs],where='post',color='#52c9b9');axes[1].scatter(xx[-1],hs[-1]['durable'],color='#52c9b9',label='Terminal health');axes[1].legend(loc='lower right');axes[1].set_ylabel('Durable detail frames');axes[1].set_xlabel('Wall seconds since first published recorder sample')
for ax in axes:ax.grid(alpha=.3)
axes[0].set_title('Final D: run: physics can finish while the archive drains');save(fig,'drain.png')
healthy=next(v for v in final['runs'] if v['definition']['name'].endswith('whole-pilot barrier'));ticks=[];forces=[];kinetic=[];trigger=healthy['metrics']['impactDetail']['triggerTick']
with (Path(healthy['archivePath'])/'detail.rort').open('rb') as f:
 f.read(32)
 while f.read(4)==b'DATA':
  n,length,crc=struct.unpack('<III',f.read(12));data=f.read(length);assert zlib.crc32(data)==crc and f.read(4)==b'DONE'
  tick,dt=struct.unpack_from('<Qd',data);nodes,beams,contacts=struct.unpack_from('<III',data,20);net=[0.,0.,0.];offset=128+nodes*256+beams*112
  for j in range(contacts):
   at=offset+j*104
   if struct.unpack_from('<I',data,at+12)[0]:
    applied=struct.unpack_from('<3f',data,at+64)
    for c in range(3):net[c]+=applied[c]
  ticks.append((tick-trigger)*dt);forces.append(net);kinetic.append(struct.unpack_from('<d',data,96)[0])
fig,axes=plt.subplots(2,1,figsize=(10,5),sharex=True)
for c,color in enumerate(['#52c9b9','#7399c1','#f7bc6a']):axes[0].plot(ticks,[f[c]/1000 for f in forces],color=color,label='XYZ'[c],lw=1)
axes[0].legend(loc='upper right');axes[0].set_ylabel('Net barrier force · kN');axes[0].set_title('Actual native detail: vector applications and movable-node kinetic energy')
axes[1].plot(ticks,[k/1000 for k in kinetic],color='#52c9b9');axes[1].set_ylabel('Kinetic energy · kJ');axes[1].set_xlabel('Physics seconds relative to first consumed barrier contact')
for ax in axes:ax.axvline(0,color='#bfcedb',ls='--',lw=.7);ax.grid(alpha=.3)
save(fig,'native-forces.png')
def url(p):return html.escape(Path(p).resolve().as_uri(),quote=True)
def image(name,caption):return '<figure><a href="'+url(media/name)+'"><img loading="lazy" src="'+url(media/name)+'" alt="'+html.escape(caption)+'"></a><figcaption>'+html.escape(caption)+' Click to open full resolution.</figcaption></figure>'
def link(p,label):return '<a href="'+url(p)+'">'+html.escape(label)+'</a>'
def table(headers,rows):return '<div class="table"><table><thead><tr>'+''.join('<th>'+h+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
before=r['timings']['baseline'];proto=r['timings']['prototypeSameDrive'];now=r['timings']['optimized'];dr=r['timings']['finalSameDriveBarrier']
mediaCheck=read(media/'playback/media-check.json');playCheck=read(media/'playback/playback-check.json');assert playCheck['webmVisiblePixels'] and playCheck['imageFallbackAdvances']
style='''<style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0a1420;color:#e1edf5;font:16px/1.65 system-ui}main{max-width:1160px;margin:auto;padding:40px 28px 70px}a{color:#66d7c8}h1{font-size:clamp(30px,5vw,52px);line-height:1.12;letter-spacing:-.025em}h2{margin-top:46px;font-size:25px}h3{font-size:19px}.eyebrow{color:#66d7c8;letter-spacing:.12em;font-size:12px}.lead{font-size:20px;color:#b8cedd}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.card,.notice{padding:22px;background:#122333;border:1px solid #2e4658;border-radius:10px}.card strong{font-size:30px;display:block;color:#66d7c8}.card small{color:#a9c0d0}.notice{border-color:#9a7342;color:#efce9c;margin:22px 0}figure{margin:26px 0}figure img{width:100%;height:auto;border:1px solid #35516a;border-radius:9px;background:#122333}figcaption{color:#96b2c6;font-size:13px;margin-top:8px}code{overflow-wrap:anywhere;color:#afd8ed}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;border-bottom:1px solid #304859;padding:12px;vertical-align:top}th{color:#66d7c8}td{overflow-wrap:anywhere}p,li{max-width:100%;overflow-wrap:anywhere}svg{max-width:100%;height:auto}.links{display:flex;gap:16px;flex-wrap:wrap}details{background:#122333;padding:14px 20px;margin:18px 0}summary{cursor:pointer;color:#66d7c8}iframe{width:100%;height:810px;border:1px solid #35516a;border-radius:9px;background:#122333}footer{margin-top:45px;color:#89a5bb;font-size:13px}@media(max-width:650px){main{padding:25px 16px}.grid{grid-template-columns:1fr}iframe{height:520px}td,th{padding:9px}}</style>'''
diagram='''<svg viewBox="0 0 1100 205" role="img" aria-label="Physics publishes bounded frames; separate recorder encodes, writes, synchronizes; coordinator verifies and workbench displays health"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#68cbbd"/></marker></defs><g fill="#172e41" stroke="#3d667d"><rect x="10" y="45" width="180" height="110" rx="8"/><rect x="225" y="45" width="180" height="110" rx="8"/><rect x="440" y="45" width="200" height="110" rx="8"/><rect x="675" y="45" width="180" height="110" rx="8"/><rect x="890" y="45" width="200" height="110" rx="8"/></g><g stroke="#68cbbd" stroke-width="2" marker-end="url(#arrow)"><path d="M190 100H215"/><path d="M405 100H430"/><path d="M640 100H665"/><path d="M855 100H880"/></g><g fill="#e1edf5" font-family="system-ui" text-anchor="middle" font-size="18"><text x="100" y="80">Native physics</text><text x="315" y="80">Bounded queue</text><text x="540" y="80">Recorder thread</text><text x="765" y="80">Coordinator</text><text x="990" y="80">Workbench</text></g><g fill="#a9c0d0" font-family="system-ui" text-anchor="middle" font-size="14"><text x="100" y="110">Every 0.5 ms</text><text x="100" y="135">Populated frame prefix</text><text x="315" y="110">Fixed reservation</text><text x="315" y="135">Pressure / high-water</text><text x="540" y="110">Encode → write → sync</text><text x="540" y="135">Distinct durability counters</text><text x="765" y="110">CRC / coverage gates</text><text x="765" y="135">Sticky incomplete quality</text><text x="990" y="110">Live + drain progress</text><text x="990" y="135">Retained results</text></g></svg>'''
parts=['<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Slice 06 · recorder hardening and performance evidence</title>',style,'</head><body><main><div class="eyebrow">RIGS OF RODS TRIALS · SLICE 06 · DEV</div><h1>Account for the recorder,<br>as well as the physics.</h1><p class="lead">Measured observer optimizations, explicit queue/write/durability health, and a corrected slow-disk flush schedule. Actual source-built simulations and independently verified archives.</p>']
parts+=['<div class="grid"><div class="card"><strong>'+f"{r['copy']['reductionFraction']*100:.1f}%"+'</strong><small>less detail producer copy traffic; required data unchanged</small></div><div class="card"><strong>'+f"{r['crc']['speedup']:.2f}×"+'</strong><small>isolated CRC throughput improvement</small></div><div class="card"><strong>12,001</strong><small>required frames per healthy window, exactly preserved</small></div></div>', '<div class="notice">The overhead target remains unmet. Final same-build full/off median ratio is '+f"{now['overheadRatio']:.3f}×"+'; the proposed aggregate ceiling is 1.10×. Vehicle scientific validation remains NotReady.</div>']
parts+=['<h2>What changed</h2>',diagram,table(['Subsystem','Implemented behavior'],[
 ('Physics observer','Skip audited inactive detail calls in aggregate-only mode; cache fixture filename during setup. Native force writes, order and random draws remain intact.'),
 ('Detail transport','Copy header, all nodes/channels, all beams, and populated contacts. Full fixed slot reservation and contact capacity remain unchanged; stale unused tails are never encoded.'),
 ('Archive integrity','Endian-safe slicing-by-eight IEEE CRC-32. Same aggregate schema 2/2080, probe schema 1/128, and detail schema 1 wire bytes.'),
 ('Durability scheduling','Start the next nominal 250 ms interval after the previous synchronization returns. Final drain and footer still force synchronization. No hard latency guarantee during blocked I/O.'),
 ('Recorder health','Independent queue depth/capacity/high-water, bytes copied, successful writes, durable frames, pending sync, loss/error, writer timings and closure. Finalizing progress is published by writers after main-thread polling stops.'),
 ('Workbench','Live pressure bars, 80% warning, write/durability separation, sticky loss, closed-writer results, and optional observer phase profiling. Historical attempts show diagnostics unavailable.'),
 ('Evidence tooling','Explicit alternate archive root, retained prototype, independent layout/CRC/state comparisons, actual UI and native visual checks.')])]
parts+=['<h2>Measured cost and its limits</h2>',image('performance.png','Median of three released-step medians per mode. D: and C: measurements are explicitly separate.'),table(['Profile','Off median µs','Full median µs','Full/off'],[(label,f"{r['timings'][key]['off']['medianOfMediansUs']:.1f}",f"{r['timings'][key]['full']['medianOfMediansUs']:.1f}",f"{r['timings'][key]['overheadRatio']:.3f}×") for label,key in [('Baseline D:','baseline'),('Optimized prototype D:','prototypeSameDrive'),('Final build C:','optimized')]]),'<p>The matched D: coast medians fell from 77.6 to 72.7 µs (6.3%). That prototype precedes the final flush-schedule repair. Final C: coast results establish the current same-build full/off ratio; cross-volume comparisons cannot isolate an algorithmic speedup. Each coast used 2 s settle + 3 s released motion, 5 m/s launch, three interleaved fresh-process repeats, OpenGL and two scheduled native screenshots. Continuous visual capture and browser UI were excluded from these budget runs.</p>',image('phases.png','Actual opt-in 10,000-step diagnostic. The solver/attribution span includes native job waits, with profiling clock overhead included.'),'<p>Off retains native trial control and the declared common probe; it is not an unmodified upstream baseline. The probe measures steady-clock step elapsed time, includes enabled ledger reduction/copy, and excludes its own sampling/queueing. The CRC microbenchmark processed 65,536,000 bytes per repeat; median byte-table time was 128.211 ms versus 30.771 ms for slicing by eight. This is a checksum benchmark, not an end-to-end simulation speedup.</p>']
parts+=['<h2>Slow-disk drain findings</h2>',image('drain.png','Final corrected D: recorder progress, independently polled while the native writers drained.'),table(['D: barrier run','Step median µs','Worker wall s','Detail sync calls'],[('Original baseline','107.5',f"{before['barrier']['workerWallSeconds']:.1f}",'not instrumented'),('Pre-cadence prototype','102.5',f"{proto['barrier']['workerWallSeconds']:.1f}",'70'),('Final corrected build',f"{dr['stepMedianUs']:.1f}",f"{dr['workerWallSeconds']:.1f}",dr['recorder']['syncCalls'])]),'<p>The prototype exposed a feedback loop: reset-before-sync made a slow flush immediately trigger another flush. The repair reduced 70 synchronization calls to 10 on these individual runs. Final D: wall time was 60.2 s, versus 91.3 s for the instrumented prototype and 52.9 s for the original baseline. Thus this evidence does not establish a general end-to-end speedup over the original build. Disk variability, shared I/O, and one run per detail variant limit that claim. The final C: barrier took '+f"{now['barrier']['workerWallSeconds']:.1f}"+' s on a different volume; it is not a matched-drive algorithm comparison.</p>', '<p>One final D: synchronization blocked for '+f"{dr['recorder']['maxSyncWallUs']/1e6:.2f}"+' s. Peak queue occupancy was 13,734 / 15,709 frames (87.4%). The separate ~3 GiB queue and 820,429,056-byte history reservation remain necessary. Producer copy traffic fell from 4,921,344,000 to 3,102,745,920 bytes; raw window payload remained 1,550,318,264 bytes. No rates, required windows, coverage thresholds or resource preflight floors were reduced.</p>']
parts+=['<h2>Exact capture and scientific scope</h2>',image('native-forces.png','Recorded force vectors and kinetic energy, computed directly from final healthy native detail. Contact work and deformation are not calibrated material dissipation.'),table(['Verification','Observed result'],[
 ('Dense required window','Four healthy captures across baseline/prototype/final D:/final C: have identical SHA-256 payload '+r['detail'][0]['payloadSha256']+'. 12,001 frames, ticks 6267–18267, 77,363 contact applications.'),
 ('Pairwise comparisons','22 pairwise checks / 276,000 paired record comparisons: zero mismatches. Aggregate accounting excludes only its declared timer field; common probe compares every-tick sentinel state and metadata plus sampled fingerprints.'),
 ('Required write failure','Final native injected partial write rolls back the partial frame, omits tick 10267, retains later frames through 18267 and records one missing tick/I/O error. Execution Completed; capture Incomplete; science NotReady. This is not physical disk exhaustion.'),
 ('Independent queue successor','The following fresh freefall attempt and spring/damper/yield fixtures complete with scoped Passed; original numerical limits are unchanged.'),
 ('Focused automated checks','Native CTest 2/2; independent bitwise CRC across unaligned buffers/tails, reused detail prefixes, and slow-sync cadence regression. Locked managed build/contracts and production React pass.'),
 ('Final managed reinspection','18 D: + 13 C: + 1 visual attempts rechecked with final coordinator readers; CRC-valid semantic transition corruptions still fail science.'),
 ('Limits','Fingerprints are diagnostic samples, not full engine checkpoints. No barrier off-mode budget, larger/multi-actor scaling, full vehicle energy closure, physical disk-full, coordinator orphan recovery or calibrated fracture qualification.')])]
parts+=['<h2>Actual workbench evidence</h2>',image('prototype-d-draining.png','Actual D: prototype UI during finalization, retained to show the queue-pressure finding before the cadence repair.'),image('healthy-closed-recorder.png','Final source build: all healthy native writers closed, zero queued/pending-sync frames.'),image('completed-recorder.png','Final source build: partial-write error remains visible after later data has been captured.'),'<p>Final Chrome checks passed: live/finalizing states, sticky fault quality, closed healthy writers, valid profiling/probe form behavior, mobile overflow and zero page errors. Historical diagnostic absence was independently checked on the retained D: prototype catalog. '+link(uiPath,'Final UI checks')+' · '+link(oldUI,'Historical-view/prototype checks')+'</p>']
parts+=['<h2>Source-built native scene and playback</h2>',image('native-after.png','Unmodified native renderer PNG from the dedicated final-build barrier recording. Visual capture is separate from performance qualification.'),'<p>'+str(len(frames))+' genuine native renderer PNGs supplied the nominal 2 fps recording. '+str(len(mediaCheck['frames']))+' decoded samples were nonblank and showed changing pixels. Chrome verified visible WebM pixels and ordinary-image progression. Codex in-app GPU video playback remains unverified; use the image player if video is blank. Playback timing is a screenshot-sequence clock, not the physical measurement clock.</p><iframe loading="lazy" title="Native image playback with optional video" src="'+url(media/'playback/playback.html')+'"></iframe><p>'+link(media/'playback/playback.html','Open image player and video')+' · '+link(media/'playback/playback-check.json','Visible-pixel verification')+' · '+link(media/'native-renderer-frame-manifest.json','Native frame provenance')+'</p>']
parts+=['<h2>Build, provenance and retained artifacts</h2>',table(['Item','Identity'],[
 ('Repository','bert-systems/rigs-of-rods-trials; dev; starting HEAD '+source['head']),
 ('Final executable SHA-256','<code>'+r['optimizedSha256']+'</code>'),
 ('Build process','Fresh native build in this unique session, then recorded incremental implementation rebuilds; VS2022/MSVC19.44 x64 Release, six jobs, existing Conan dependency cache. Focused native tests also build Release.'),
 ('Source verification',str(len(inputs))+' native/CMake input hashes match the final working source. Compilation preceded commit; Git version metadata records the starting dirty build, with source hashes identifying the exact implementation.'),
 ('Process proof','Every native process path/hash and loaded module inventory verified. Private source-built workers supplied executable/DLLs; installed root game and protected October 8 baseline were preserved.'),
 ('D: evidence',str(root)+'; original baseline, prototype, final cadence run, build logs, UI/media and report.'),
 ('C: evidence',str(Path(healthy['archivePath']).parent)+'; final qualification. Dedicated visual archive '+str(Path(v['archivePath']).parent)+'.'),
 ('Retention','All recorded originals remain. No automatic archive/data cleanup. Portable review bundle contains source/logs/metadata, aggregate/probe/fixture raw records and media; full dense originals remain inventoried at their declared archive paths.')]),'<div class="links">'+link(buildPath,'Final build record')+link(sourcePath,'Native input inventory')+link(resultPath,'Independent analysis')+link(Path(build['nativeLog']),'Native build / CTest log')+link(report/'slice-06-review.zip','Portable review bundle')+'</div>']
parts+=['<h2>Next implementation slice</h2><p>Qualify later collision-induced yield, strength degradation and beam removal with controlled impact fixtures and independent checks. Broader nonlinear/vehicle energy closure and calibrated material dissipation remain subsequent work. Continue optimizing the dominant solver/attribution phase and qualify overhead on larger scenes before accepting the proposed budgets. Development and publication stay on dev; periodic master pull requests remain user-managed.</p><footer>Evidence session started 2026-10-09, America/New_York. Generated '+time.strftime('%Y-%m-%d %H:%M:%S')+'. Native capture remains separate from scoped scientific acceptance.</footer></main></body></html>']
dest=repo/'doc/project/reports/trial-slice-06-2026-10-09.html';dest.write_text(''.join(parts),encoding='utf-8')
(report/'report-inputs.json').write_text(json.dumps(dict(html=str(dest),media=str(media),analysis=str(resultPath),finalBuild=str(buildPath),nativeInputsVerified=len(inputs),nativeSha256=r['optimizedSha256'],ui=str(uiPath),visualAttempt=v['id']),indent=2),encoding='utf-8')
print(str(dest))
